language: python
dist: xenial

notifications:
  slack:
    rooms:
      secure: $slack_not
    on_success: change
    on_failure: always

matrix:
  include:
    - python: 3.7

before_install:
  - sudo apt-get update

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov=stuff --cov=test
  - flake8 . --exit-zero # Exit with status code "0" even if there are errors.

after_success:
  - coveralls
