language: python
dist: xenial
notifications:
  slack:
    secure: t6nxctSG2hUZ5stNP6el4nTm9OboAWQVfuxV1mUuYc2ab1LM6EqnnlZcHCAJMPFEKFrMR/S6Z8iAYMOMYIqfaLjrU7WLi/MAaYsnA/8RqDLVKu+0oqG7gGCL/xuj5DV3K9Gi3biGGdAQVMRXbGEx0W5UacDVMtJiCsdDK1YULyxtoE0NHUAKHpIxdH1jbENbakYJfMUjpAaH+n7BIpmg3JIGgekSER+hmEH/pKaoPmOFMbOhi33SB+x+Ujftp3Feqc+3VjpfjLkIlUvr/j0hGgACfOnxF7PjQ+5Ofwad9QjB7BQv5yJxz61jRwL0/F2ElzBTUlxdQWkbXE+nt3YNKw6s3djdu6ouBCiyHPWuibwEt4GwvMawc9DdcMZjk3aQlsdSoXpVGwEaJ8gstkGabHAbzDr0PCctBRxZsBxqS7GM5sDVXjK66GgOyWRe+2TwlIzSoXyXEos4IL8QK4aRDZGdAO0ACSQGv+MaVULkKJoWw79oigTYA2bzeIA5Asu7Xc/kkOVZdqZG69JE+Rq63O6JAEnF9kwZT/varuVyP5EherqlCQk0uVZgQIdQIZ+aTLT53bKnnk4eqbRl7GMvhhOAnGbhTwnJFD2MF6XObXk3l3lAr42Cz9SgmmyzjX536OKY96rzT1q4BP1X1H5mYlHu/supoTgXgxQvSy/nIL4=
  on_success: change
  on_failure: always
matrix:
  include:
  - python: 3.7
before_install:
- sudo apt-get update
install:
- pip install -r requirements.txt
script:
- pytest --cov=stuff --cov=test
- flake8 . --exit-zero
after_success:
- coveralls
